### ISSUE TITLE
client failed to connect to node

### ISSUE THREAD

**Issue by atankvadi** [RobotnikAutomation/robotnik_base_hw#1]
i am working on Rb1
To connect my laptop to the RB-1 base

first
**mcq-1@mcq-linux-1:~$ sudo vim.tiny /etc/hosts**
inside this host file I add **192.168.0.200    rb1**
**mcq-1@mcq-linux-1:~$ ssh rb1@192.168.0.200**,  I did, and its login successfully 

then
**rb1@rb1-demo:~$ sudo vim.tiny /etc/hosts**
 inside this host file I add **192.168.0.152       mcq-1**

now after **roscore** and **export ROS_MASTER_URI=http://rb1:11311**, I can see all **rostopic, rosservice** and **rosnode.**

but when i try see the value of topic, it saying that 
**mcq-1@mcq-linux-1:~$ rostopic echo /rb1_base/rb1_base_control/odom 
WARNING: no messages received and simulated time is active.
Is /clock being published?**

so i am trying with **rqt** to see the value of topic, but I found
![screenshot from 2018-06-14 14-05-10](https://user-images.githubusercontent.com/39796468/41413695-2457fe06-6fe4-11e8-9263-8dea6c716ad9.png)

am I missing something?
please let me know why it is happening,

**Comment by RomanRobotnik** [comment]
Hi @atankvadi ,

In your /etc/hosts file you have to set correctly the robot's hostname:

_192.168.0.200  rb1-demo # not just rb1_

Thus, you need to set the ROS_MASTER_URI as:

 _ROS_MASTER_URI=http://rb1-demo:11311_

Then, you have to apply the same in the robot hosts:

_192.168.0.152 mcq-linux-1_

It looks like you're using the _username_ instead of the _hostname_. 

Hope it helps,
